import type { Locale } from '../stores/localeStore';

type AgentTextMap = Record<Locale, Record<string, string[]>>;

const TOOL_START_TEXTS: AgentTextMap = {
  en: {
    Bash: [
      'Running a command...',
      'Executing in terminal...',
      'Shell time!',
      'Let me run this...',
      'Firing up the terminal',
      'sudo make me a sandwich',
      'Bashing away',
      'chmod 777 everything — just kidding',
      'Hope this doesn\'t break anything',
      'Crossing fingers and pressing enter',
      'Into the shell we go',
      'Let\'s see what happens',
      'Terminal go brrrr',
      'One does not simply run commands',
      'Trust the process',
      'Executing order 66',
      'What could possibly go wrong?',
      'Running something sketchy...',
      'Computer says yes',
      'Unleashing the command',
      'This better work',
      'Hold my coffee',
      'Engaging turbo mode',
    ],
    Write: [
      'Writing code...',
      'Creating a file...',
      'Putting this together...',
      'Time to write!',
      'Composing code...',
      'Fresh code incoming',
      'Birthing a new file',
      'Writing beautiful code',
      'Poetry in TypeScript',
      'Manifesting a file',
      'New file, who dis?',
      'Conjuring code from thin air',
      'Here comes a masterpiece',
      'It\'s alive!',
      'Let there be code',
      'Writing my magnum opus',
      'From zero to file',
      'Blank canvas, let\'s go',
      'Building something new',
      'Crafting fresh code',
    ],
    Edit: [
      'Editing code...',
      'Tweaking the code...',
      'Making changes...',
      'Refactoring here...',
      'Adjusting this...',
      'Just a small fix',
      'Surgery on the codebase',
      'Polishing the code',
      'Nip and tuck',
      'Improving this bit',
      'Touching up the code',
      'A little edit never hurt anyone',
      'Fine-tuning...',
      'Making it better, I promise',
      'Rearranging the furniture',
      'Code makeover time',
      'Sculpting the code',
      'A tweak here, a tweak there',
      'Fixing what ain\'t broken — wait',
      'The code needed this',
      'Performing code surgery',
      'Slight adjustment',
    ],
    Read: [
      'Reading files...',
      'Let me check this...',
      'Looking at the code...',
      'Studying the source...',
      'Hmm, interesting file',
      'Absorbing knowledge',
      'Reading... reading... reading',
      'Let me see what we\'ve got',
      'Peeking at the code',
      'Ah yes, code',
      'Taking a look',
      'Let me understand this first',
      'Investigating the source',
      'Who wrote this? Oh wait',
      'Deciphering ancient runes',
      'Reading the fine print',
      'Analyzing the situation',
      'What do we have here?',
      'Interesting, very interesting',
      'Opening the scroll',
      'Consuming the docs',
      'Let me just read this real quick',
    ],
    Grep: [
      'Searching code...',
      'Looking for patterns...',
      'Where is that thing?',
      'Scanning the codebase...',
      'Grep grep grep...',
      'Finding the needle in the haystack',
      'Detective mode activated',
      'Where did that go?',
      'Searching far and wide',
      'I know it\'s in here somewhere',
      'Following the trail...',
      'It\'s gotta be here',
      'Code archaeology',
      'Hunting for clues',
      'Like finding Waldo',
      'On the hunt',
      'Sniffing out the code',
      'Where art thou, code?',
      'Seeking and hopefully finding',
      'Playing hide and seek with code',
    ],
    Glob: [
      'Looking for files...',
      'Finding files...',
      'Where are those files?',
      'Scanning directories...',
      'Let me find that...',
      'Exploring the file tree',
      'Searching the maze of folders',
      'File hunting season',
      'Navigating the file system',
      'Where did I put that?',
      'Folder diving',
      'Lost in the directory tree',
      'File safari',
      'Checking the map',
      'So many files, so little time',
      'Browsing the shelves',
      'In search of files',
      'Rummaging through folders',
    ],
    Task: [
      'Thinking it through...',
      'Delegating a task...',
      'Spinning up a helper...',
      'Let me plan this...',
      'Breaking this down...',
      'Sending a minion',
      'Deploying reinforcements',
      'Calling for backup',
      'Assembling the team',
      'Divide and conquer',
      'Help me help you',
      'Outsourcing the thinking',
      'Spawning a clone',
      'Getting help from a friend',
      'Two heads are better than one',
      'This needs more brains',
      'Tag team!',
      'Summoning assistance',
      'Brain expansion pack',
      'Let me get a second opinion',
    ],
    WebSearch: [
      'Searching the web...',
      'Let me look this up...',
      'Googling it...',
      'Researching online...',
      'Checking the internet...',
      'Asking the oracle',
      'To the internet!',
      'Let me consult Stack Overflow',
      'Browsing the web',
      'What does the internet say?',
      'Surely someone has done this before',
      'Time to research',
      'Consulting the hive mind',
      'Down the rabbit hole',
      'Wiki-walking',
      'Asking the cloud',
      'The internet knows all',
      'Let me Google that for me',
      'Searching for answers',
    ],
    WebFetch: [
      'Fetching a page...',
      'Downloading content...',
      'Grabbing that URL...',
      'Loading a webpage...',
      'Pulling data from the web...',
      'Fetching, like a good dog',
      'Downloading the internet',
      'HTTP GET incoming',
      'Reaching into the web',
      'Bringing back treasures',
      'Loading page, please wait',
      'Snatching data',
      'Fishing for content',
      'Reeling in a page',
      'Web grab in progress',
    ],
    Skill: [
      'Using a skill...',
      'Activating skill mode...',
      'Let me use this tool...',
      'Skill engaged!',
      'Special ability!',
      'Unlocking a power-up',
      'Using my special move',
      'Ultimate ability ready',
      'Activating secret weapon',
      'Going Super Saiyan',
      'Power level rising',
      'Deploying the big guns',
      'Time to show off',
      'Watch this',
      'Level up!',
    ],
    _default: [
      'Working on it...',
      'Let me use this tool...',
      'Processing...',
      'Doing the thing...',
      'On it!',
      'Busy busy busy',
      'Hang tight',
      'Bear with me',
      'Magic in progress',
      'Something is happening',
      'Give me a sec',
      'Crunching away',
      'Working my magic',
      'I got this',
      'Almost there — maybe',
      'Let me handle this',
      'Wizardry in progress',
      'Beep boop',
      'Doing important stuff',
      'Just a moment',
      'Watch and learn',
      'Computing intensifies',
    ],
  },
  de: {
    Bash: [
      'Führe Befehl aus...',
      'Ab ins Terminal...',
      'Shell-Zeit!',
      'Lass mich das ausführen...',
      'Terminal wird gestartet...',
      'sudo mach mir ein Sandwich',
      'Drücke Enter und hoffe',
      'Hoffentlich geht nix kaputt',
      'Daumen drücken',
      'Ab in die Shell',
      'Mal schauen was passiert',
      'Terminal geht brrrr',
      'Was kann schon schiefgehen?',
      'Führe was Verdächtiges aus...',
      'Computer sagt ja',
      'Halt mein Kaffee',
      'Turbo-Modus aktiviert',
      'Das muss funktionieren',
      'Befehl wird losgelassen',
      'Vertrau dem Prozess',
      'Los geht\'s im Terminal',
      'Order 66 wird ausgeführt',
    ],
    Write: [
      'Schreibe Code...',
      'Erstelle eine Datei...',
      'Baue das zusammen...',
      'Zeit zum Schreiben!',
      'Verfasse Code...',
      'Frischer Code im Anmarsch',
      'Erschaffe eine neue Datei',
      'Schreibe wunderschönen Code',
      'Poesie in TypeScript',
      'Manifestiere eine Datei',
      'Neue Datei, wer dis?',
      'Beschwore Code aus dem Nichts',
      'Hier kommt ein Meisterwerk',
      'Es lebt!',
      'Es werde Code',
      'Schreibe mein Magnum Opus',
      'Von Null zur Datei',
      'Leere Leinwand, los',
      'Baue was Neues',
      'Frischen Code basteln',
    ],
    Edit: [
      'Bearbeite Code...',
      'Passe den Code an...',
      'Änderungen vornehmen...',
      'Refactoring hier...',
      'Justiere das...',
      'Nur eine kleine Änderung',
      'Operation am offenen Code',
      'Poliere den Code',
      'Hier ein Schnitt, da ein Schnitt',
      'Verbessere dieses Stückchen',
      'Code aufhübschen',
      'Ein kleines Edit hat nie geschadet',
      'Feintuning...',
      'Mach es besser, versprochen',
      'Möbel umstellen im Code',
      'Code-Makeover',
      'Code wird geformt',
      'Hier ändern, da ändern',
      'Repariere was nicht kaputt — Moment',
      'Der Code brauchte das',
      'Code-Chirurgie',
      'Kleine Anpassung',
    ],
    Read: [
      'Lese Dateien...',
      'Lass mich das prüfen...',
      'Schaue mir den Code an...',
      'Studiere den Quelltext...',
      'Hmm, interessante Datei',
      'Sauge Wissen auf',
      'Lesen, lesen, lesen',
      'Mal schauen was wir haben',
      'Spicke in den Code',
      'Ah ja, Code',
      'Werfe einen Blick drauf',
      'Erst mal verstehen',
      'Untersuche den Quelltext',
      'Wer hat das geschrieben? Oh',
      'Entziffere alte Runen',
      'Lese das Kleingedruckte',
      'Analysiere die Lage',
      'Was haben wir denn hier?',
      'Interessant, sehr interessant',
      'Öffne die Schriftrolle',
      'Konsumiere die Doku',
      'Nur kurz lesen',
    ],
    Grep: [
      'Durchsuche Code...',
      'Suche nach Mustern...',
      'Wo ist das Ding?',
      'Scanne die Codebase...',
      'Grep grep grep...',
      'Nadel im Heuhaufen suchen',
      'Detektiv-Modus aktiviert',
      'Wo ist das hin?',
      'Suche weit und breit',
      'Ich weiss, es ist hier irgendwo',
      'Folge der Spur...',
      'Muss hier irgendwo sein',
      'Code-Archäologie',
      'Jage nach Hinweisen',
      'Wie Walter suchen',
      'Auf der Jagd',
      'Schnüffele im Code',
      'Wo bist du, Code?',
      'Suchen und hoffentlich finden',
      'Versteckspiel mit dem Code',
    ],
    Glob: [
      'Suche Dateien...',
      'Finde Dateien...',
      'Wo sind diese Dateien?',
      'Durchsuche Verzeichnisse...',
      'Lass mich das finden...',
      'Erkunde den Dateibaum',
      'Durchsuche das Ordner-Labyrinth',
      'Datei-Jagdsaison',
      'Navigiere das Dateisystem',
      'Wo hab ich das hingelegt?',
      'Tauche in Ordner ein',
      'Verirrt im Verzeichnisbaum',
      'Datei-Safari',
      'Prüfe die Karte',
      'So viele Dateien, so wenig Zeit',
      'Durchstöbere die Regale',
      'Auf der Suche nach Dateien',
      'Wühle durch Ordner',
    ],
    Task: [
      'Denke darüber nach...',
      'Delegiere eine Aufgabe...',
      'Starte einen Helfer...',
      'Lass mich das planen...',
      'Zerlege das Problem...',
      'Schicke einen Diener los',
      'Verstärkung wird deployed',
      'Rufe nach Backup',
      'Stelle das Team zusammen',
      'Teile und herrsche',
      'Hilf mir, dir zu helfen',
      'Outsource das Denken',
      'Spawne einen Klon',
      'Hole Hilfe von einem Freund',
      'Zwei Köpfe sind besser als einer',
      'Das braucht mehr Hirn',
      'Tag-Team!',
      'Beschwore Unterstützung',
      'Gehirn-Erweiterungspaket',
      'Hole mir eine zweite Meinung',
    ],
    WebSearch: [
      'Suche im Web...',
      'Lass mich nachschlagen...',
      'Googeln...',
      'Recherchiere online...',
      'Checke das Internet...',
      'Frage das Orakel',
      'Ab ins Internet!',
      'Konsultiere Stack Overflow',
      'Surfe durchs Web',
      'Was sagt das Internet?',
      'Das hat bestimmt schon jemand gemacht',
      'Zeit für Recherche',
      'Konsultiere den Schwarm',
      'Ab in den Kaninchenbau',
      'Wiki-Wanderung',
      'Frage die Cloud',
      'Das Internet weiß alles',
      'Google ich halt für mich',
      'Suche nach Antworten',
    ],
    WebFetch: [
      'Lade eine Seite...',
      'Lade Inhalt herunter...',
      'Hole die URL...',
      'Lade Webseite...',
      'Ziehe Daten aus dem Web...',
      'Apportiere, wie ein braver Hund',
      'Lade das Internet herunter',
      'HTTP GET eingehend',
      'Greife ins Web',
      'Bringe Schätze mit',
      'Seite wird geladen, bitte warten',
      'Schnappe mir Daten',
      'Angle nach Inhalten',
      'Ziehe eine Seite ein',
      'Web-Zugriff läuft',
    ],
    Skill: [
      'Nutze einen Skill...',
      'Aktiviere Skill-Modus...',
      'Lass mich das Tool nutzen...',
      'Skill aktiviert!',
      'Spezialfähigkeit!',
      'Schalte ein Power-Up frei',
      'Nutze meinen Spezialzug',
      'Ultimative Fähigkeit bereit',
      'Aktiviere Geheimwaffe',
      'Werde zum Super-Saiyajin',
      'Power-Level steigt',
      'Fahre die großen Geschütze auf',
      'Zeit zum Angeben',
      'Guck mal',
      'Level hoch!',
    ],
    _default: [
      'Arbeite daran...',
      'Lass mich das Tool nutzen...',
      'Verarbeite...',
      'Mache das Ding...',
      'Bin dran!',
      'Fleißig, fleißig',
      'Gleich geschafft — vielleicht',
      'Einen Moment noch',
      'Magie im Gange',
      'Da passiert was',
      'Gib mir ne Sekunde',
      'Knuspere daran',
      'Zaubere',
      'Ich hab das',
      'Gleich fertig — vielleicht',
      'Lass mich das regeln',
      'Zauberei in Arbeit',
      'Piep piep',
      'Mache wichtige Sachen',
      'Nur einen Moment',
      'Schau und lerne',
      'Rechnen intensiviert sich',
    ],
  },
};

const CATEGORY_TEXTS: AgentTextMap = {
  en: {
    permission_wait: [
      'Waiting for approval...',
      'Need permission here...',
      'Awaiting the green light...',
      'Can I do this? Asking...',
      'Hold on, need approval...',
      'Pretty please?',
      'Boss, can I?',
      'Excuse me, may I?',
      'Permission slip needed',
      'Waiting for the go-ahead...',
      'Standing by for clearance',
      'Bureaucracy at its finest',
      'Rubber stamp needed',
      'Knock knock, can I enter?',
      'Security checkpoint',
      'Need authorization',
      'Patiently waiting...',
      'Red tape moment',
      'Please say yes',
      'The bouncer won\'t let me in',
    ],
    subagent_start: [
      'Delegating to a sub-agent...',
      'Sending a helper off...',
      'Splitting the work...',
      'Sub-agent activated!',
      'Teamwork makes the dream work',
      'Summoning a minion',
      'Cloning myself',
      'Deploying the intern',
      'Calling in reinforcements',
      'Another me, but smaller',
      'Help is on the way',
      'Spawning a worker bee',
      'Offloading brain work',
      'Parallel universe me is on it',
      'My people will call your people',
      'Engaging worker drone',
      'Mini-me to the rescue',
      'Sending out a scout',
      'Distributing the workload',
    ],
    subagent_end: [
      'Sub-agent is done!',
      'Helper reported back',
      'Got the results!',
      'Sub-agent finished',
      'Back from delegation',
      'The minion returns',
      'Mission accomplished',
      'Intel received',
      'Clone reporting in',
      'Helper earned their paycheck',
      'Report from the field',
      'Data has landed',
      'Worker bee returned to hive',
      'The intern survived!',
      'Scout returned with findings',
      'Task force reporting',
      'Results are in',
      'That was quick',
      'Helper nailed it',
    ],
    session_start: [
      'Clocking in!',
      'Ready to work!',
      'Let\'s get started!',
      'Good to be here',
      'Time to code!',
      'Another day, another repo',
      'Who\'s ready to code?',
      'Let\'s build something',
      'Coffee loaded, let\'s go',
      'Booting up...',
      'Hello world!',
      'Entering the matrix',
      'Brain cells: activated',
      'The code awaits',
      'Morning! Wait, what time is it?',
      'Systems online',
      'Reporting for duty',
      'Fresh and ready',
      'Let\'s make some magic',
      'Time to earn my tokens',
      'Warmed up and ready',
      'The keyboard is calling',
    ],
    session_end: [
      'All done for now',
      'Signing off!',
      'Work complete',
      'Time to head out',
      'See you next time!',
      'That\'s a wrap',
      'Dropping the mic',
      'Logging off',
      'My work here is done',
      'Until next time',
      'Task complete, peace out',
      'Clocking out',
      'Saving progress and leaving',
      'Gone fishin\'',
      'Exiting the matrix',
      'BRB — or maybe not',
      'Off into the sunset',
      'Shutting down gracefully',
      'Catch you later',
      'End of line',
      'Tschüss!',
    ],
    turn_end: [
      'Thinking...',
      'What\'s next?',
      'Taking a moment...',
      'Processing...',
      'Let me think...',
      'Hmm...',
      'Brain loading...',
      'Contemplating the universe',
      'Pondering life choices',
      'Loading next thought...',
      'Wait for it...',
      'Synapse firing',
      'Buffering...',
      'The gears are turning',
      'One moment...',
      'Brb thinking',
      'Compiling thoughts...',
      'Almost had it',
      'That\'s a good question actually',
      'Neurons at work',
      'Deep in thought',
      'Let me cook',
    ],
    idle_notification: [
      '*yawns*',
      'Stretching...',
      'Anyone there?',
      'Twiddling my thumbs...',
      'Waiting around...',
      'Nothing to do right now',
      'Staring into space',
      'Humming a tune...',
      'Taking a breather',
      'On standby',
      'Idle hands...',
      'Just vibing',
      'Watching the clock',
      'Daydreaming...',
      'Counting pixels',
    ],
    elicitation_wait: [
      'Waiting for your answer...',
      'Need your input here...',
      'Got a question for you...',
      'Your turn to decide...',
      'What do you think?',
      'Over to you!',
      'Awaiting your response...',
      'The ball is in your court',
      'Need a decision here...',
      'Patiently waiting for input...',
      'Can\'t proceed without you...',
      'Your call!',
      'Waiting on your expertise...',
      'Need your two cents...',
      'Standing by for your answer...',
    ],
    auth_success: [
      'Authenticated!',
      'Logged in!',
      'Access granted!',
      'We\'re in!',
      'Credentials accepted',
      'Identity confirmed',
      'Auth successful!',
      'The door is open',
      'Keys accepted',
      'Welcome back!',
      'Login complete',
      'Verified!',
      'All clear!',
      'Badge accepted',
      'Green light!',
    ],
    worktree_create: [
      'Setting up workspace...',
      'Creating a worktree...',
      'Branching out...',
      'New workspace incoming',
      'Preparing isolated environment...',
      'Spawning a worktree',
      'Building a sandbox',
      'Fresh workspace ready',
      'Workspace under construction',
      'Carving out space...',
      'New branch, new beginnings',
      'Isolating the work area',
      'Workspace assembly...',
      'Getting my own desk',
      'Setting up camp',
    ],
    worktree_remove: [
      'Cleaning up workspace...',
      'Removing worktree...',
      'Tidying up...',
      'Workspace teardown',
      'Packing up the desk',
      'Cleanup crew reporting',
      'Dismantling the sandbox',
      'Workspace decommissioned',
      'Folding up shop',
      'Sweeping the floor',
      'Breaking down camp',
      'Workspace archived',
      'All packed up',
      'Leaving it clean',
      'Done with this space',
    ],
    teammate_idle: [
      'Teammate is idle...',
      'My colleague is waiting',
      'Someone\'s twiddling thumbs',
      'Team member on standby',
      'Partner is free',
      'Colleague taking a break',
      'Buddy is available',
      'Teammate on hold',
      'Co-worker chilling',
      'Team friend is idle',
      'My partner waits...',
      'Another agent is free',
      'Office buddy is bored',
      'Team member stretching',
      'Colleague staring at ceiling',
    ],
    task_completed: [
      'Task complete!',
      'Nailed it!',
      'Mission accomplished!',
      'Done and done!',
      'Another one bites the dust',
      'Checked off the list!',
      'That\'s a wrap!',
      'Achievement unlocked!',
      'High five!',
      'Boom, done!',
      'One less thing to worry about',
      'Finished!',
      'Gold star earned',
      'And the crowd goes wild',
      'That was satisfying',
    ],
  },
  de: {
    permission_wait: [
      'Warte auf Genehmigung...',
      'Brauche hier Erlaubnis...',
      'Warte auf grünes Licht...',
      'Darf ich? Frage nach...',
      'Moment, brauche Freigabe...',
      'Bitte bitte?',
      'Chef, darf ich?',
      'Entschuldigung, darf ich?',
      'Erlaubnisschein nötig',
      'Warte auf das Go...',
      'Stehe bereit für Freigabe',
      'Bürokratie vom Feinsten',
      'Stempel nötig',
      'Klopf klopf, darf ich rein?',
      'Sicherheitskontrolle',
      'Brauche Autorisierung',
      'Warte geduldig...',
      'Bürokratie-Moment',
      'Bitte sag ja',
      'Der Türsteher lässt mich nicht rein',
    ],
    subagent_start: [
      'Delegiere an Sub-Agent...',
      'Schicke einen Helfer los...',
      'Teile die Arbeit auf...',
      'Sub-Agent aktiviert!',
      'Teamarbeit',
      'Beschwore einen Diener',
      'Klone mich selbst',
      'Setze den Praktikanten ein',
      'Rufe Verstärkung',
      'Noch ein Ich, aber kleiner',
      'Hilfe ist unterwegs',
      'Spawne eine Arbeitsbiene',
      'Lagere Denkarbeit aus',
      'Parallel-Universum-Ich ist dran',
      'Meine Leute rufen deine Leute',
      'Aktiviere Arbeitsdrohne',
      'Mini-Ich zur Rettung',
      'Schicke einen Späher',
      'Verteile die Arbeitslast',
    ],
    subagent_end: [
      'Sub-Agent ist fertig!',
      'Helfer hat berichtet',
      'Ergebnisse sind da!',
      'Sub-Agent abgeschlossen',
      'Zurück von der Delegation',
      'Der Diener kehrt zurück',
      'Mission erfüllt',
      'Intel empfangen',
      'Klon meldet sich',
      'Helfer hat sich den Lohn verdient',
      'Bericht vom Feld',
      'Daten sind gelandet',
      'Arbeitsbiene zurück im Stock',
      'Der Praktikant hat überlebt!',
      'Späher mit Ergebnissen zurück',
      'Einsatztruppe meldet',
      'Ergebnisse liegen vor',
      'Das ging schnell',
      'Helfer hat\'s drauf',
    ],
    session_start: [
      'Stempel rein!',
      'Bereit zum Arbeiten!',
      'Los geht\'s!',
      'Schön hier zu sein',
      'Zeit zum Coden!',
      'Ein neuer Tag, ein neues Repo',
      'Wer ist bereit zum Coden?',
      'Lass uns was bauen',
      'Kaffee geladen, los',
      'Hochfahren...',
      'Hallo Welt!',
      'Betrete die Matrix',
      'Gehirnzellen: aktiviert',
      'Der Code wartet',
      'Morgen! Warte, wie spät ist es?',
      'Systeme online',
      'Melde mich zum Dienst',
      'Frisch und bereit',
      'Lass uns zaubern',
      'Zeit, meine Tokens zu verdienen',
      'Aufgewärmt und startklar',
      'Die Tastatur ruft',
    ],
    session_end: [
      'Erstmal fertig',
      'Melde mich ab!',
      'Arbeit erledigt',
      'Zeit zu gehen',
      'Bis zum nächsten Mal!',
      'Das war\'s',
      'Mikro wird fallen gelassen',
      'Logge mich aus',
      'Meine Arbeit hier ist getan',
      'Bis dann',
      'Aufgabe erledigt, Tschüss',
      'Stempel raus',
      'Speichere und gehe',
      'Bin dann mal Angeln',
      'Verlasse die Matrix',
      'BRB — oder vielleicht nicht',
      'Ab in den Sonnenuntergang',
      'Fahre ordentlich herunter',
      'Bis später',
      'Ende der Zeile',
      'Bye bye!',
    ],
    turn_end: [
      'Nachdenken...',
      'Was kommt als Nächstes?',
      'Kurzer Moment...',
      'Verarbeite...',
      'Lass mich überlegen...',
      'Hmm...',
      'Gehirn lädt...',
      'Betrachte das Universum',
      'Überdenke Lebensentscheidungen',
      'Lade nächsten Gedanken...',
      'Gleich kommt\'s...',
      'Synapse feuert',
      'Puffere...',
      'Die Zahnräder drehen sich',
      'Einen Moment...',
      'Bin kurz denken',
      'Kompiliere Gedanken...',
      'Hatte es fast',
      'Gute Frage eigentlich',
      'Neuronen bei der Arbeit',
      'Tief in Gedanken',
      'Lass mich kochen',
    ],
    idle_notification: [
      '*gähn*',
      'Strecke mich...',
      'Jemand da?',
      'Drehe Däumchen...',
      'Warte rum...',
      'Gerade nichts zu tun',
      'Starre ins Leere',
      'Summe ein Lied...',
      'Mache Pause',
      'Im Standby',
      'Untätige Hände...',
      'Chillen einfach',
      'Schaue auf die Uhr',
      'Tagträume...',
      'Zähle Pixel',
    ],
    elicitation_wait: [
      'Warte auf deine Antwort...',
      'Brauche deine Eingabe...',
      'Habe eine Frage an dich...',
      'Du bist dran zu entscheiden...',
      'Was denkst du?',
      'Du bist dran!',
      'Warte auf deine Antwort...',
      'Der Ball liegt bei dir',
      'Brauche eine Entscheidung...',
      'Warte geduldig auf Eingabe...',
      'Kann ohne dich nicht weiter...',
      'Dein Aufruf!',
      'Warte auf dein Fachwissen...',
      'Brauche deinen Senf...',
      'Stehe bereit für deine Antwort...',
    ],
    auth_success: [
      'Authentifiziert!',
      'Eingeloggt!',
      'Zugang gewährt!',
      'Wir sind drin!',
      'Anmeldedaten akzeptiert',
      'Identität bestätigt',
      'Auth erfolgreich!',
      'Die Tür ist offen',
      'Schlüssel akzeptiert',
      'Willkommen zurück!',
      'Login abgeschlossen',
      'Verifiziert!',
      'Alles klar!',
      'Ausweis akzeptiert',
      'Grünes Licht!',
    ],
    worktree_create: [
      'Richte Workspace ein...',
      'Erstelle Worktree...',
      'Verzweige mich...',
      'Neuer Workspace kommt',
      'Bereite isolierte Umgebung vor...',
      'Spawne einen Worktree',
      'Baue eine Sandbox',
      'Frischer Workspace bereit',
      'Workspace im Aufbau',
      'Schaffe Platz...',
      'Neuer Branch, neuer Anfang',
      'Isoliere den Arbeitsbereich',
      'Workspace-Montage...',
      'Bekomme meinen eigenen Schreibtisch',
      'Schlage Lager auf',
    ],
    worktree_remove: [
      'Räume Workspace auf...',
      'Entferne Worktree...',
      'Aufräumen...',
      'Workspace-Abbau',
      'Packe den Schreibtisch zusammen',
      'Aufräumtrupp meldet sich',
      'Demontiere die Sandbox',
      'Workspace stillgelegt',
      'Mache den Laden dicht',
      'Fege den Boden',
      'Baue das Lager ab',
      'Workspace archiviert',
      'Alles eingepackt',
      'Hinterlasse es sauber',
      'Fertig mit diesem Platz',
    ],
    teammate_idle: [
      'Teamkollege wartet...',
      'Mein Kollege wartet',
      'Jemand dreht Däumchen',
      'Teammitglied im Standby',
      'Partner ist frei',
      'Kollege macht Pause',
      'Kumpel ist verfügbar',
      'Teamkollege in der Warteschleife',
      'Mitarbeiter chillt',
      'Teamfreund ist untätig',
      'Mein Partner wartet...',
      'Ein anderer Agent ist frei',
      'Büro-Kumpel langweilt sich',
      'Teammitglied streckt sich',
      'Kollege starrt an die Decke',
    ],
    task_completed: [
      'Aufgabe erledigt!',
      'Geschafft!',
      'Mission erfüllt!',
      'Fertig und fertig!',
      'Noch einer erledigt',
      'Von der Liste gestrichen!',
      'Das war\'s!',
      'Erfolg freigeschaltet!',
      'High Five!',
      'Bumm, fertig!',
      'Eine Sorge weniger',
      'Abgeschlossen!',
      'Goldstern verdient',
      'Und die Menge tobt',
      'Das war befriedigend',
    ],
  },
};

function pickRandom(arr: string[]): string {
  return arr[Math.floor(Math.random() * arr.length)]!;
}

export function getAgentBubbleText(
  locale: Locale,
  category: string,
  toolName?: string,
): string {
  if (category === 'tool_start') {
    const toolTexts = TOOL_START_TEXTS[locale];
    const name = toolName ?? '';
    const mcpPrefix = 'mcp__';
    if (name.startsWith(mcpPrefix)) {
      const service = name.split('__')[1] ?? 'service';
      const templates =
        locale === 'de'
          ? [`Nutze ${service}...`, `${service} wird verwendet...`]
          : [`Using ${service}...`, `Calling ${service}...`];
      return pickRandom(templates);
    }
    const texts = toolTexts[name] ?? toolTexts['_default']!;
    return pickRandom(texts);
  }

  const categoryTexts = CATEGORY_TEXTS[locale];
  const texts = categoryTexts[category];
  if (!texts) {
    return locale === 'de' ? 'Arbeite...' : 'Working...';
  }
  return pickRandom(texts);
}
